### ISSUE TITLE
Unable to Open Project

### ISSUE THREAD

**Issue by hbina** [pop-os/cosmic-edit#288]
**Cosmic-edit version:**

master

**Issue/Bug description:**

**Steps to reproduce:**

1. git clone
2. run in debug mode
3. try to Open Project

**Expected behavior:**

**Other notes:**

The stacktrace

```
hbina085@akarin ~/g/cosmic-edit (master) [SIGINT]> RUST_BACKTRACE=1 cargo run
   Compiling cosmic-edit v0.1.0 (/home/hbina085/git/cosmic-edit)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 1m 25s
     Running `target/debug/cosmic-edit`
[2024-12-28T14:33:52Z WARN  sctk_adwaita::buttons] Ignoring unknown button type: 
[2024-12-28T14:33:53Z WARN  wgpu_hal::gles::egl] Re-initializing Gles context due to Wayland window
[2024-12-28T14:33:53Z WARN  sctk_adwaita::buttons] Ignoring unknown button type: 
thread 'main' panicked at /home/hbina085/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/b524ccb/iced/futures/src/subscription.rs:249:9:
the closure fn(cosmic_files::dialog::DialogMessage) -> cosmic_edit::Message provided in `Subscription::map` is capturing
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/90b35a6239c3d8bdabc530a6a0816f7ff89a0aaf/library/core/src/panicking.rs:74:14
   2: iced_futures::subscription::Subscription<T>::map
             at /home/hbina085/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/b524ccb/iced/futures/src/subscription.rs:249:9
   3: cosmic_files::dialog::Dialog<M>::subscription
             at /home/hbina085/.cargo/git/checkouts/cosmic-files-6338c402b47773da/42c0d58/src/dialog.rs:251:9
   4: <cosmic_edit::App as cosmic::app::Application>::subscription
             at ./src/main.rs:3032:33
   5: cosmic::app::cosmic::Cosmic<T>::subscription
             at /home/hbina085/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/b524ccb/src/app/cosmic.rs:190:13
   6: core::ops::function::Fn::call
             at /home/hbina085/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:79:5
   7: <iced::program::with_subscription::WithSubscription<P,F> as iced::program::Program>::subscription
             at /home/hbina085/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/b524ccb/iced/src/program.rs:298:13
   8: <iced::program::with_style::WithStyle<P,F> as iced::program::Program>::subscription
             at /home/hbina085/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/b524ccb/iced/src/program.rs:469:13
   9: <iced::program::with_theme::WithTheme<P,F> as iced::program::Program>::subscription
             at /home/hbina085/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/b524ccb/iced/src/program.rs:399:13
  10: <iced::program::Program::run_with::Instance<P,I> as iced_winit::program::Program>::subscription
             at /home/hbina085/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/b524ccb/iced/src/program.rs:155:17
  11: iced_winit::program::update::{{closure}}
             at /home/hbina085/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/b524ccb/iced/winit/src/program.rs:1915:41
  12: <cosmic::executor::single::Executor as iced_futures::executor::Executor>::enter
             at /home/hbina085/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/b524ccb/src/executor/single.rs:31:9
  13: iced_futures::runtime::Runtime<Executor,Sender,Message>::enter
             at /home/hbina085/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/b524ccb/iced/futures/src/runtime.rs:50:9
  14: iced_winit::program::update
             at /home/hbina085/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/b524ccb/iced/winit/src/program.rs:1915:24
  15: iced_winit::program::run_instance::{{closure}}
             at /home/hbina085/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/b524ccb/iced/winit/src/program.rs:1572:21
  16: iced_winit::program::run::Runner<Message,F,C>::process_event
             at /home/hbina085/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/b524ccb/iced/winit/src/program.rs:453:28
  17: <iced_winit::program::run::Runner<Message,F,C> as winit::application::ApplicationHandler>::about_to_wait
             at /home/hbina085/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/b524ccb/iced/winit/src/program.rs:345:13
  18: <&mut A as winit::application::ApplicationHandler>::about_to_wait
             at /home/hbina085/.cargo/git/checkouts/winit-40d7deb2b0c08730/1cc02bd/src/application.rs:374:9
  19: <&mut A as winit::application::ApplicationHandler>::about_to_wait
             at /home/hbina085/.cargo/git/checkouts/winit-40d7deb2b0c08730/1cc02bd/src/application.rs:374:9
  20: winit::platform_impl::linux::wayland::event_loop::EventLoop::single_iteration
             at /home/hbina085/.cargo/git/checkouts/winit-40d7deb2b0c08730/1cc02bd/src/platform_impl/linux/wayland/event_loop/mod.rs:468:9
  21: winit::platform_impl::linux::wayland::event_loop::EventLoop::poll_events_with_timeout
             at /home/hbina085/.cargo/git/checkouts/winit-40d7deb2b0c08730/1cc02bd/src/platform_impl/linux/wayland/event_loop/mod.rs:270:9
  22: winit::platform_impl::linux::wayland::event_loop::EventLoop::pump_app_events
             at /home/hbina085/.cargo/git/checkouts/winit-40d7deb2b0c08730/1cc02bd/src/platform_impl/linux/wayland/event_loop/mod.rs:191:13
  23: winit::platform_impl::linux::wayland::event_loop::EventLoop::run_app_on_demand
             at /home/hbina085/.cargo/git/checkouts/winit-40d7deb2b0c08730/1cc02bd/src/platform_impl/linux/wayland/event_loop/mod.rs:154:19
  24: winit::platform_impl::linux::wayland::event_loop::EventLoop::run_app
             at /home/hbina085/.cargo/git/checkouts/winit-40d7deb2b0c08730/1cc02bd/src/platform_impl/linux/wayland/event_loop/mod.rs:145:9
  25: winit::platform_impl::linux::EventLoop::run_app
             at /home/hbina085/.cargo/git/checkouts/winit-40d7deb2b0c08730/1cc02bd/src/platform_impl/linux/mod.rs:427:56
  26: winit::event_loop::EventLoop::run_app
             at /home/hbina085/.cargo/git/checkouts/winit-40d7deb2b0c08730/1cc02bd/src/event_loop.rs:228:9
  27: iced_winit::program::run
             at /home/hbina085/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/b524ccb/iced/winit/src/program.rs:632:17
  28: iced::program::Program::run_with
             at /home/hbina085/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/b524ccb/iced/src/program.rs:183:12
  29: cosmic::app::multi_window::MultiWindow<P>::run_with
             at /home/hbina085/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/b524ccb/src/app/multi_window.rs:124:9
  30: cosmic::app::run
             at /home/hbina085/.cargo/git/checkouts/libcosmic-b367e32ffc370f4f/b524ccb/src/app/mod.rs:170:9
  31: cosmic_edit::main
             at ./src/main.rs:178:5
  32: core::ops::function::FnOnce::call_once
             at /home/hbina085/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by iamkartiknayak** [comment]
This issue seems to have been fixed.
